### DISCUSSION TITLE
Can't install plugins via ETHERPAD_PLUGINS build arg in docker-compose.yml

### DISCUSSION THREAD

**Discussion by narthur** [ether/etherpad-lite#6366] [Q&A]
I'm trying to install plugins via the ETHERPAD_PLUGINS build arg in my docker-compose.yml file, and having no luck. The only plugin that shows up in the admin dashboard is `ep_etherpad-lite`. What am I doing wrong?

Here's the command I'm using to spin up the instance:

```bash
docker-compose up --build --force-recreate --always-recreate-deps
```

And here's the docker-compose file:

```yaml
version: "3"

services:
  etherpad:
    image: etherpad/etherpad:2.0.3
    build:
      # context: .
      args:
        # - ETHERPAD_PLUGINS="ep_adminpads3 ep_author_hover ep_brightcolorpicker ep_pad_activity_nofication_in_title ep_post_data ep_prompt_for_name ep_sync_status"
        - ETHERPAD_PLUGINS="ep_author_hover"
        # - ETHERPAD_LOCAL_PLUGINS="ep_simple_urls"
        - SETTINGS=./settings.json
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_PASS=secretpassword
      - ADMIN_PASSWORD=secretpassword
      - IMPORT_EXPORT_MAX_REQ_PER_IP=1000
    ports:
      - "9001:9001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=etherpad
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=etherpad
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:

```

**Comment by narthur** [comment]
@SamTV12345 Sorry to bother you but do you have any suggestions on how I can debug this?

**Comment by SamTV12345** [comment]
> I'm trying to install plugins via the ETHERPAD_PLUGINS build arg in my docker-compose.yml file, and having no luck. The only plugin that shows up in the admin dashboard is `ep_etherpad-lite`. What am I doing wrong?
> 
> Here's the command I'm using to spin up the instance:
> 
> ```shell
> docker-compose up --build --force-recreate --always-recreate-deps
> ```
> 
> And here's the docker-compose file:
> 
> ```yaml
> version: "3"
> 
> services:
>   etherpad:
>     image: etherpad/etherpad:2.0.3
>     build:
>       # context: .
>       args:
>         # - ETHERPAD_PLUGINS="ep_adminpads3 ep_author_hover ep_brightcolorpicker ep_pad_activity_nofication_in_title ep_post_data ep_prompt_for_name ep_sync_status"
>         - ETHERPAD_PLUGINS="ep_author_hover"
>         # - ETHERPAD_LOCAL_PLUGINS="ep_simple_urls"
>         - SETTINGS=./settings.json
>     restart: always
>     environment:
>       - DB_TYPE=postgres
>       - DB_HOST=postgres
>       - DB_PORT=5432
>       - DB_NAME=etherpad
>       - DB_USER=etherpad
>       - DB_PASS=secretpassword
>       - ADMIN_PASSWORD=secretpassword
>       - IMPORT_EXPORT_MAX_REQ_PER_IP=1000
>     ports:
>       - "9001:9001"
>     depends_on:
>       - postgres
> 
>   postgres:
>     image: postgres
>     restart: always
>     environment:
>       - POSTGRES_USER=etherpad
>       - POSTGRES_PASSWORD=secretpassword
>       - POSTGRES_DB=etherpad
>     volumes:
>       - postgres-data:/var/lib/postgresql/data
>     ports:
>       - "5432:5432"
> 
> volumes:
>   postgres-data:
> ```

Please try the official one and just add the build context and the environment variable. We have new docs hosted here: https://docs.etherpad.org/docker.html . Hope this helps you and if you have any other problem with Etherpad just ask :)


```yaml
services:
  app:
    build:
      args:
        - ETHERPAD_PLUGINS=ep_author_hover
      context: .
    user: "0:0"
    image: etherpad/etherpad:latest
    tty: true
    stdin_open: true
    volumes:
      - plugins:/opt/etherpad-lite/src/plugin_packages
      - etherpad-var:/opt/etherpad-lite/var
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${DOCKER_COMPOSE_APP_ADMIN_PASSWORD:-admin}
      DB_CHARSET: ${DOCKER_COMPOSE_APP_DB_CHARSET:-utf8mb4}
      DB_HOST: postgres
      DB_NAME: ${DOCKER_COMPOSE_POSTGRES_DATABASE:-etherpad}
      DB_PASS: ${DOCKER_COMPOSE_POSTGRES_PASSWORD:-admin}
      DB_PORT: ${DOCKER_COMPOSE_POSTGRES_PORT:-5432}
      DB_TYPE: "postgres"
      DB_USER: ${DOCKER_COMPOSE_POSTGRES_USER:-admin}
      # For now, the env var DEFAULT_PAD_TEXT cannot be unset or empty; it seems to be mandatory in the latest version of etherpad
      DEFAULT_PAD_TEXT: ${DOCKER_COMPOSE_APP_DEFAULT_PAD_TEXT:- }
      DISABLE_IP_LOGGING: ${DOCKER_COMPOSE_APP_DISABLE_IP_LOGGING:-false}
      SOFFICE: ${DOCKER_COMPOSE_APP_SOFFICE:-null}
      TRUST_PROXY: ${DOCKER_COMPOSE_APP_TRUST_PROXY:-true}
    restart: always
    ports:
      - "${DOCKER_COMPOSE_APP_PORT_PUBLISHED:-9001}:${DOCKER_COMPOSE_APP_PORT_TARGET:-9001}"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DOCKER_COMPOSE_POSTGRES_DATABASE:-etherpad}
      POSTGRES_PASSWORD: ${DOCKER_COMPOSE_POSTGRES_PASSWORD:-admin}
      POSTGRES_PORT: ${DOCKER_COMPOSE_POSTGRES_PORT:-5432}
      POSTGRES_USER: ${DOCKER_COMPOSE_POSTGRES_USER:-admin}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # Exposing the port is not needed unless you want to access this database instance from the host.
    # Be careful when other postgres docker container are running on the same port
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
  plugins:
  etherpad-var:

```
