### ISSUE TITLE
Docker volume configuration help

### ISSUE THREAD

**Issue by Eluminae** [ether/etherpad-lite#3581]
Hello all,
I need help about the docker volume configuration. I'd like to know the good way to keep persistence.
My config is for now:
```
volumes:
  - app-storage:/opt/etherpad-lite
  - /etc/localtime:/etc/localtime:ro
```

I'm voluming for:

* Persist modules installation
* Persist auto generated keys (Session, etc)

> I got an external postgres container that persist pads and other things.

But I'm questionning myself:

* Is there any other way to persist my needs without using volumes?
* Does this setup allow code upgrade, upgrading the docker image?
  * An entrypoint script (nextcloud's like) couldn't be needed?

What are you experience returns about this points?

**Comment by Pr0gmaT1k** [comment]
UP, I would like to know if it's possible, simply, to use postgres or my SQL instead of dirty.db inside a docker build.
Maybe a docker-compose.yml ?

**Comment by Eluminae** [comment]
It is possible.
I link my old docker stack. It should still work and it use a postgres service.
https://git.sr.ht/~reedwade/etherpad_stack/tree/master

There was a bug with the postgres-etherpad socket. I hope it will not cause you troubles.

**Comment by Pr0gmaT1k** [comment]
please, could you be more explicit about the postgres configration ?

**Comment by Eluminae** [comment]
I just gave you the docker-compose. I cannot be more precise

```
  db:
    image: postgres:11-alpine
    volumes:
      - db-storage:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: etherpad
      POSTGRES_PASSWORD: etherpad
      POSTGRES_DB: etherpad
    networks:
      db: ~
```
