### ISSUE TITLE
Persisting plugins on the docker host 

### ISSUE THREAD

**Issue by pecuchet** [ether/etherpad-lite#3582]
Hello,
I'm running etherpad-lite through docker (`17.05.0-ce, build 89658b`). It works well, but when I restart the container, plugins which were installed through the admin interface are lost.  

I thought it would only require bind-mounting the plugin folders to the docker host, but the symlink (`ep_etherpad-lite -> ../src`) located in `/opt/etherpad-lite/node_modules` does not seem to survive the mounting &mdash; even if the file paths of the container are mimicked on the host like below. 

Any ideas on how to fix this? 

```
version: '3.4'

services:
  etherpad:
    build: .
    container_name: etherpad
    networks:
      - my-network
    volumes:
      - ./settings.json:/opt/etherpad-lite/settings.json:ro
      - /opt/etherpad-lite/var:/opt/etherpad-lite/var
      - /opt/etherpad-lite/node_modules:/opt/etherpad-lite/node_modules
      - /opt/etherpad-lite/src:/opt/etherpad-lite/src
    environment:
      - NODE_ENV=production

networks:
  my-network:
    external:
      name: ${DOCKER_NETWORK}
```

The container throws the following error upon startup:
```
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/opt/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```
