### ISSUE TITLE
[Chrome] Ok button on index page not aligned

### ISSUE THREAD

**Issue by CupCakeArmy** [ether/etherpad-lite#3604]
I was trying out the new theme (which btw is absolutely awesome!) and I have some style issues on chrome. (Firefox and Safari work fine)

<img width="400" alt="Screenshot 2019-05-08 at 13 27 48" src="https://user-images.githubusercontent.com/14948823/57372305-8790f280-7195-11e9-9d35-953b8d60ff4c.png">

The OK button is bad positioned.

```css
button[type=submit] {
    border-top-right-radius: 3px;
    border-bottom-right-radius: 3px;
    left: 305px;
    border: none;
    top: 0; // <-- This fixes the issue
}
```

This fixes the issue without breaking safari or firefox.
