### ISSUE TITLE
Continual page refreshing when running the Etherpad docker container behind an NGINX Ingress controller on Kubernetes

### ISSUE THREAD

**Issue by cypher0n3** [ether/etherpad-lite#4123]
When using the docker container on a Kubernetes cluster behind an NGINX ingress controller, in an open pad, the page continually refreshes.  This happens in both Firefox and Chromium; tested from a Fedora 31 system. EDIT: It is worth noting that the pad does get updates from multiple editors still and actively typing in the page appears to prevent refreshes at least while typing.

Removing the container from behind the ingress controller and giving it its own IP on the load balancer resolves this issue.

Example Kubernetes config which results in continual page refreshes:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: etherpad
    labels:
        app: etherpad
spec:
    replicas: 1
    selector:
        matchLabels:
            app: etherpad
    template:
        metadata:
            labels:
                app: etherpad
        spec:
            containers:
                -   name: etherpad
                    image: etherpad/etherpad:latest
                    ports:
                        -   name: http
                            containerPort: 9001
                    imagePullPolicy: Always
            restartPolicy: Always
...

---
apiVersion: v1
kind: Service
metadata:
    name: etherpad-service
spec:
    selector:
        app: etherpad
    ports:
        -   name: http
            protocol: TCP
            port: 80
            targetPort: 9001
...

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: etherpad-ingress
    annotations:
        ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        -   host: etherpad.dom.com
            http:
                paths:
                    -   path: /
                        backend:
                            serviceName: etherpad-service
                            servicePort: 80
...
```

Example Kubernetes config which does not experience page refreshes:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: etherpad
    labels:
        app: etherpad
spec:
    replicas: 1
    selector:
        matchLabels:
            app: etherpad
    template:
        metadata:
            labels:
                app: etherpad
        spec:
            containers:
                -   name: etherpad
                    image: etherpad/etherpad:latest
                    ports:
                        -   name: http
                            containerPort: 9001
                    imagePullPolicy: Always
            restartPolicy: Always
...

---
apiVersion: v1
kind: Service
metadata:
    name: etherpad-service
spec:
    externalTrafficPolicy: Local
    type: LoadBalancer
    selector:
        app: etherpad
    ports:
        -   name: http
            protocol: TCP
            port: 80
            targetPort: 9001
    loadBalancerIP: 192.168.100.121
...
```
