### ISSUE TITLE
Docker-compose etherpad container with database container

### ISSUE THREAD

**Issue by etienneleba** [ether/etherpad-lite#4214]
**Describe the bug**
Hi,
I'm trying to link my etherpad container to a database (mariadb database) but it's not working and I'm not figuring out why. I tried to build the image by myself but it doesn't work

**To Reproduce**
1. create a docker-compose file with this lines : 
```
db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

 etherpad:
    image: etherpad/etherpad
    ports:
      - ${ETHERPAD_PORT}:9001
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_TYPE: "maria"
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_CHARSET: utf8mb4
```
**Expected behavior**
It should work, but I'm getting this error :
```
etherpad_1  | internal/modules/cjs/loader.js:638
etherpad_1  |     throw err;
etherpad_1  |     ^
etherpad_1  | 
etherpad_1  | Error: Cannot find module './databases/maria_db'
etherpad_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
etherpad_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
etherpad_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
etherpad_1  |     at require (internal/modules/cjs/helpers.js:25:18)
etherpad_1  |     at new exports.database (/opt/etherpad-lite/src/node_modules/ueberdb2/index.js:37:20)
etherpad_1  |     at Object.<anonymous> (/opt/etherpad-lite/src/node/db/DB.js:28:10)
etherpad_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
etherpad_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
etherpad_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
etherpad_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Desktop (please complete the following information):**
 - OS: ubuntu
