### ISSUE TITLE
docker etherpad stress test [QUESTION]

### ISSUE THREAD

**Issue by etienneleba** [ether/etherpad-lite#4411]
Hi everyone,

I'm developing an app which is using an etherpad instance. My goal is to put 100 people on the app, dispatched on 20 pads. First question, I don't have any clue about the etherpad performance, so is it realistic ? if yes, how many cpu and memory I should take ? 

I wanted to answer to this question by myself so I created a t2.micro node on aws and I put a dockerize etherpad on it with this config : 
```yml
# docker-compose.yml
version: "3.3"

services:
  etherpad:
    build:
      context: https://github.com/ether/etherpad-lite.git#release/1.8.5
      args:
        ETHERPAD_PLUGINS: "ep_align ep_author_hover ep_comments_page ep_copy_paste_images ep_headings2 ep_who_did_what"
    ports:
      - 80:9001
    environment:
      ADMIN_PASSWORD: "*****"
      LOAD_TEST: "true"

```
I cloned the repo etherpad-load-test and I launched the tests. The result was that the t2.micro (1 cpu, 1GB memory) can handle around 40 users on one pad. It's not enough for me, so I tried the same config on a t2.medium (2 cpus, 4GB memory) and I had the same result, also around 40 users. 
So I checked the cpu and the memory of the aws node during the tests and they were used only at 10% on the t2.medium and 15% on the t2.micro. 

So my question is who is the limiting factor ? docker ? etherpad server ? Generally, the containers can use what they want of the host, so I do not understand why it is not using more than 10% of cpu and memory. 

I suppose you have done many stress tests before, so if someone has a clue, could you explain me plz :smile: 

Have a nice day !
