### ISSUE TITLE
Problem with import. Upload failed. Error 400 Bad Request

### ISSUE THREAD

**Issue by pandiloko** [ether/etherpad-lite#4808]
**Import File doesn't work**
I can't import a text file. I searched through existing issues and can't find a similar problem. I thought it was my nginx config but I finally tested without plugins and directly calling the backend with http://myserverip:9001 and the problem was there. 

**To Reproduce**

Etherpad running through docker-compose in an updated Ubuntu Server 20.04

```
version: "3"

services:
  server:
    image: etherpad/etherpad
    restart: always
    environment:
      - ADMIN_PASSWORD=secretpassword
    volumes:
      - /opt/docker-etherpad/data:/opt/etherpad-lite/var
    ports:
      - "9001:9001"
```

**Expected behavior**
Text file should be imported and replace the text with its contents.

**Desktop:**
 - OS: KDE Neon (Ubuntu 20.04)
 - Browser Firefox 85 and Chromium 88

**Additional context**
Error says:
 Import failed: The upload failed, please try again
The Browser shows a 400 Bad Request error:
and as response:

`{"code":1,"message":"uploadFailed","data":{}}`

I don't see anything in the docker logs.
