### ISSUE TITLE
Google Chrome cant load document

### ISSUE THREAD

**Issue by Y0ngg4n** [ether/etherpad-lite#4976]
**Describe the bug**
The Bug only appears in Google Chrome Browser and not in Firefox

**To Reproduce**
Open this Etherpad file in Google Chrome:
[Demo](https://etherpad.oblivioncoding.pro/p/aborea?showControls=true&showChat=false&showLineNumbers=true&useMonospaceFont=false)

**Expected behavior**
Loading the Document

**Screenshots**
![image](https://user-images.githubusercontent.com/30302975/112539671-9399f380-8db1-11eb-91d0-dc772d51f780.png)

**Server (please complete the following information):**
 - Etherpad version: Docker latest
 - OS: Debian
 - Node.js version (`node --version`): v14.16.0
 - npm version (`npm --version`): 6.14.11

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Chrome
 - Version: Version 89.0.4389.90 (Offizieller Build) (64-Bit)

**Comment by webzwo0i** [comment]
confirmed

**Comment by Y0ngg4n** [comment]
I have build the etherpad docker image about 1h ago with following build args:
```
etherpad: 
        build:
            context: etherpad-lite/.
            args:
                - ETHERPAD_PLUGINS=ep_markdown ep_headings2 ep_align ep_tables3 ep_whiteboard ep_image_upload ep_subscript_and_superscript ep_cursortrace ep_comments_page ep_font_color ep_font_family ep_embedmedia ep_mammoth ep_embedded_hyperlinks2 ep_countable ep_print ep_mathjax
```

- ep_markdown: 0.1.30
- ep_headings2: 0.2.26
- ep_align: 0.3.31
- ep_tables3: 0.3.14
- ep_whiteboard: 0.0.4
- ep_image_upload: 1.0.43
- ep_subscript_and_superscript: 1.0.43
- ep_cursortrace: 3.1.7
- ep_comments_page: 0.1.60
- ep_font_color: 0.0.40
- ep_font_family: 0.5.29
- ep_embedmedia: 0.0.18
- ep_mammoth: 0.1.11
- ep_embedded_hyperlinks2: 1.2.2
- ep_countable: 0.0.9
- ep_print: 0.1.1
- ep_mathjax: 0.1.10
