### ISSUE TITLE
Change the BaseURL of the Node Application

### ISSUE THREAD

**Issue by massih10** [ether/etherpad-lite#5134]
Hi, I built a simple Kubernetes deployment for the stable Docker Image of etherpad-lite. I'm trying to set up an ingress rule with lets say https://somedomain/etherpad. I can get the application to be shown, but etherpad is looking for all static files under https://somedomain/ instead of https://somedomain/etherpad/ .... Does anyone know how to change the app root of the web application? I found (https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy
But not sure how to transfer this into a kubernetes ingress rule. Also the base path under https://somedomain/ is already used by another application. I believe I need to change something on the side of the source code of etherpad, not on the server configuration side. Could you provide some instructions how to set up the Docker Image for a custom BaseURL? Help would be much appreciated!

Here my ingress rule:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: etherpad
  namespace: etherpad
spec:
  rules:
  - host: somedomain
    http:
      paths:
      - path:  /etherpad(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: etherpad
            port:
              number: 80
```
![Unbenannt](https://user-images.githubusercontent.com/65487879/127483495-f178ddcc-5eb2-48b3-b304-f0c4a1019b76.JPG)
