### ISSUE TITLE
docker-compose example

### ISSUE THREAD

**Issue by perrotuerto** [ether/etherpad-lite#5169]
This is related to #4634

I leave a working example here:

``` 
version: '3.1'
services:
  web:
    image: etherpad/etherpad
    depends_on:
      - mydb
    ports:
      - "9001:9001"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=mydb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=etherpad
      - DB_PASS=mydbpass
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mydbpass
      - POSTGRES_USER=etherpad
```

**Comment by Manumie** [comment]
In order to install plugins from the admin page and persist them into the container, much more comfortable than building them into the image (which doesn't always work), you can mount your container in a persistent Docker volume :
```
version: '3.1'
services:
  web:
    image: etherpad/etherpad
    depends_on:
      - mydb
    ports:
      - "9001:9001"
    volumes:
      - pad_vol:/opt/etherpad-lite
    environment:
      - DB_TYPE=postgres
      - DB_HOST=mydb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=etherpad
      - DB_PASS=mydbpass
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mydbpass
      - POSTGRES_USER=etherpad

  volumes:
     pad_vol:
```

_(not tested)_ - It might also ease the use of such plugins as `ep_hash_auth` if you set its path to a subdir within the volume (in `settings.json` ) : 
```
 "ep_hash_auth": {
    "hash_dir": "/opt/etherpad-lite/var/etherpad/users",
  },
```
For what it's worth...
