### ISSUE TITLE
Cannot change settings via webinterface (/admin/settings) using docker(-compose)

### ISSUE THREAD

**Issue by timaschew** [ether/etherpad-lite#5246]
I'm using this docker-compose file:

```yml
version: '3.1'
services:
  web:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    environment:
      - ADMIN_PASSWORD=******
    volumes:
      - "/root/etherpad-docker/data:/opt/etherpad-lite"
```

I've tried to change the settings via the webinterface (`/admin/settings`) for the toolbar, but the file content shown in the browser is not stored in`/opt/etherpad-lite/settings.json` but still the content is somewhere persisted because a page refresh and even server restart shows same content (but without that it's used). The content in the webinterrace also differs from the content in `/opt/etherpad-lite/settings.json`.
