### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by tessierp** [ether/etherpad-lite#5643]
I installed the latest docker etherpad/etherpad and I am unable to install plugins. When I select to install one, I get the notification of installing at the top but it never installs. If I refresh, the list is empty. No error message whatsoever.

![image](https://user-images.githubusercontent.com/6784384/202467285-97c1903b-120a-40b6-a96d-a182843823f5.png)

`
[2022-11-17 09:00:19.372] [INFO] server - Etherpad is running

[2022-11-17 09:00:39.985] [INFO] http - Successful authentication from IP 10.0.0.2 for user admin

[2022-11-17 09:00:40.131] [ERROR] console - Error: Request aborted

    at onaborted (/opt/etherpad-lite/src/node_modules/express/lib/response.js:1025:15)

    at Immediate.<anonymous> (/opt/etherpad-lite/src/node_modules/express/lib/response.js:1067:9)

    at processImmediate (internal/timers.js:464:21)

[2022-11-17 09:00:44.962] [INFO] plugins - Installing plugin ep_adminpads2...

[2022-11-17 09:03:07.388] [INFO] plugins - Installing plugin ep_delete_after_delay...

[2022-11-17 09:03:21.297] [INFO] Minify - Compress JS file js/vendors/html10n.js.

[2022-11-17 09:03:21.298] [INFO] Minify - Compress JS file js/l10n.js.

[2022-11-17 09:03:21.320] [INFO] Minify - Compress CSS file skins/colibris/index.css.

[2022-11-17 09:03:21.335] [INFO] Minify - Compress JS file skins/colibris/index.js.

[2022-11-17 09:03:44.336] [INFO] plugins - Installing plugin ep_adminpads2...

[2022-11-17 09:03:45.719] [INFO] plugins - Installing plugin ep_aa_file_menu_toolbar.
`

**Comment by fab-kaz** [comment]
hello,

same here, unable to install from web admin interface.

Moreover, here is my Dockerfile, may be i missed something, i thought it as possible to load plugins from Dockerfile.

```
cat Dockerfile
FROM etherpad/etherpad:1.8.18
ARG ETHERPAD_PLUGINS="ep_headings2"
```

bug logs show ep_headings2 isn't installed.

thank you and regards,

f.

**Comment by weed-** [comment]
Same here, I am unable to install plugins from web admin interface. No Docker setup, just plain install.

```
npm --version 6.14.15
node --version v19.1.0
etherpad 1.8.18
```
Log:

`[INFO] plugins - Installing plugin ep_align...`

(nothing more).

**Comment by weed-** [comment]
Update: Installing plugins with `npm install --no-save --legacy-peer-deps ep_$plugin` breaks the installation completely.

**Comment by Leobaillard** [comment]
Same here on NodeJS v14.

**Comment by aQwus** [comment]
I was able to install the plugin successfully on localhost but facing an issue in production. I have hosted my etherpad on aws ec2.
```
npm --version 6.14.17
node --version v14.21.0
etherpad 1.8.18
```

Terminal displays that I have successfully installed the plugin but when fetching for installed plugins, it fetchs only `ep_etherpad-lite`

Terminal while installing plugin:
```
Installing plugin ep_image_upload...



[2022-12-07 07:27:34.517] [ERROR] runCmd|npm - npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[2022-12-07 07:27:37.746] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad/etherpad-lite/package.json'
[2022-12-07 07:27:37.759] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
[2022-12-07 07:27:37.777] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
[2022-12-07 07:27:37.790] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
[2022-12-07 07:27:37.802] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
[2022-12-07 07:27:37.803] [ERROR] runCmd|npm - 
[2022-12-07 07:27:37.804] [INFO] runCmd|npm - + ep_image_upload@1.0.92
[2022-12-07 07:27:37.805] [INFO] runCmd|npm - removed 1 package, updated 1 package, moved 28 packages and audited 1386 packages in 8.469s
[2022-12-07 07:27:38.472] [INFO] runCmd|npm - 
[2022-12-07 07:27:38.472] [INFO] runCmd|npm - 95 packages are looking for funding
[2022-12-07 07:27:38.472] [INFO] runCmd|npm -   run `npm fund` for details
[2022-12-07 07:27:38.473] [INFO] runCmd|npm - 
[2022-12-07 07:27:38.474] [INFO] runCmd|npm - found 36 vulnerabilities (2 low, 5 moderate, 29 high)
[2022-12-07 07:27:38.475] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
[2022-12-07 07:27:38.496] [INFO] plugins - Successfully installed plugin ep_image_upload
[2022-12-07 07:27:38.496] [INFO] plugins - Running npm to get a list of installed plugins...
[2022-12-07 07:27:42.561] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2022-12-07 07:27:42.562] [INFO] plugins - Loaded 1 plugins
```

**Comment by tessierp** [comment]
> I was able to install the plugin successfully on localhost but facing an issue in production. I have hosted my etherpad on aws ec2.
> 
> ```
> npm --version 6.14.17
> node --version v14.21.0
> etherpad 1.8.18
> ```
> 
> Terminal displays that I have successfully installed the plugin but when fetching for installed plugins, it fetchs only `ep_etherpad-lite`
> 
> Terminal while installing plugin:
> 
> ```
> Installing plugin ep_image_upload...
> 
> 
> 
> [2022-12-07 07:27:34.517] [ERROR] runCmd|npm - npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> [2022-12-07 07:27:37.746] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad/etherpad-lite/package.json'
> [2022-12-07 07:27:37.759] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
> [2022-12-07 07:27:37.777] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
> [2022-12-07 07:27:37.790] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
> [2022-12-07 07:27:37.802] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
> [2022-12-07 07:27:37.803] [ERROR] runCmd|npm - 
> [2022-12-07 07:27:37.804] [INFO] runCmd|npm - + ep_image_upload@1.0.92
> [2022-12-07 07:27:37.805] [INFO] runCmd|npm - removed 1 package, updated 1 package, moved 28 packages and audited 1386 packages in 8.469s
> [2022-12-07 07:27:38.472] [INFO] runCmd|npm - 
> [2022-12-07 07:27:38.472] [INFO] runCmd|npm - 95 packages are looking for funding
> [2022-12-07 07:27:38.472] [INFO] runCmd|npm -   run `npm fund` for details
> [2022-12-07 07:27:38.473] [INFO] runCmd|npm - 
> [2022-12-07 07:27:38.474] [INFO] runCmd|npm - found 36 vulnerabilities (2 low, 5 moderate, 29 high)
> [2022-12-07 07:27:38.475] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
> [2022-12-07 07:27:38.496] [INFO] plugins - Successfully installed plugin ep_image_upload
> [2022-12-07 07:27:38.496] [INFO] plugins - Running npm to get a list of installed plugins...
> [2022-12-07 07:27:42.561] [INFO] plugins - Loading plugin ep_etherpad-lite...
> [2022-12-07 07:27:42.562] [INFO] plugins - Loaded 1 plugins
> ```

Would you mind explaining how you were able to do this, a step by step procedure? When you say you were able to install on localhost I presume you mean you actually logged into the container itself and installed it correct? Not sure if that is what you have done but if it is, you realize that it will only be valid for that one time and as soon as the container is recreated it will be gone.

**Comment by aQwus** [comment]
@tessierp I cloned the etherpad repo into my local device. Then ran it on localhost, logged into the admin portal([localhost](http://localhost:9001/admin/plugins)) and installed the plugin from there. It worked on localhost.

I then hosted etherpad on an ec2 instance and again tried installing the plugin through the [admin portal](http://0.0.0.0/admin/plugins). The stack trace which I added above is from the ec2 terminal, which shows the status of the plugin being installed through the admin portal. But it did not work on production, as evident from the stack trace.

**Comment by tessierp** [comment]
Thanks for the clarification @aQwus , much appreciated!

**Comment by aQwus** [comment]
Since I am unable to install plugins using the admin portal, I installed them via code.

```
cd $PATH/TO/ETHERPAD_LITE
npm i plugin_name
```

After the installation, restart the Etherpad. You should be able to use the Etherpad with plugins installed.

**Comment by tommyhlw** [comment]
same issue here:

[2023-01-16 20:32:45.957] [INFO] plugins - npm --version: 6.14.15
[2023-01-16 20:32:49.207] [INFO] console - Your Etherpad version is 1.8.18 (4b96ff6)

> Since I am unable to install plugins using the admin portal, I installed them via code.
> 
> ```
> cd $PATH/TO/ETHERPAD_LITE
> npm i plugin_name
> ```
> 
> After the installation, restart the Etherpad. You should be able to use the Etherpad with plugins installed.

trying this, the installation freezes:
`/opt/etherpad-lite$ npm i ep_openid_connect
[      ............] / fetchMetadata: sill resolveWithNewModule yallist@4.0.0 checking installable status`

**Comment by tommyhlw** [comment]
For. me this looks like a bug in 1.8.18
just tested with a blank volume and docker image 1.8.14 and 1.8.15
There the plugin installation worked like a charm
However stell get warnings:
`pad_3_1     | [2023-01-25 02:15:55.899] [INFO] plugins - Installing plugin ep_adminpads2...
pad_3_1     | [2023-01-25 02:16:04.888] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
pad_3_1     | [2023-01-25 02:16:04.899] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
pad_3_1     | [2023-01-25 02:16:04.911] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
pad_3_1     | [2023-01-25 02:16:04.921] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
pad_3_1     | [2023-01-25 02:16:04.931] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
pad_3_1     | [2023-01-25 02:16:04.932] [ERROR] runCmd|npm - 
pad_3_1     | [2023-01-25 02:16:05.116] [INFO] runCmd|npm - + ep_adminpads2@2.1.57
pad_3_1     | [2023-01-25 02:16:05.117] [INFO] runCmd|npm - added 24 packages from 8 contributors and audited 1164 packages in 8.728s
pad_3_1     | [2023-01-25 02:16:05.551] [INFO] runCmd|npm - 
pad_3_1     | [2023-01-25 02:16:05.552] [INFO] runCmd|npm - 68 packages are looking for funding
pad_3_1     | [2023-01-25 02:16:05.552] [INFO] runCmd|npm -   run `npm fund` for details
pad_3_1     | [2023-01-25 02:16:05.552] [INFO] runCmd|npm - 
pad_3_1     | [2023-01-25 02:16:05.554] [INFO] runCmd|npm - found 105 vulnerabilities (1 low, 14 moderate, 68 high, 22 critical)
pad_3_1     | [2023-01-25 02:16:05.554] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
pad_3_1     | [2023-01-25 02:16:05.598] [INFO] plugins - Successfully installed plugin ep_adminpads2
`

**Comment by tommyhlw** [comment]
`But another problem occurs: when i docker-compose down && up -d, the plugin previously installed have all disappeared.`
I guess you need add Volume were the plugins will BE installed and persisted

**Comment by fab-kaz** [comment]
thank you @tommyhlw , that's what i did. one volume and one file :

In my docker-compose.yml:
```
      - etherpadPlugins:/opt/etherpad-lite/node_modules/
      - ${PWD}/settings.json:/opt/etherpad-lite/settings.json

```

I must add that i could simply install plugin with the web admin interface with the 1.8.18 version. The first plugin is very loooong to install, about 10 minutes, then the others are fast.

well, with the lastest version, with persistent volume for plugins, i guess everything is ok with etherpad now.

Thank you everybody.

Maybe we should close this ticket ?

**Comment by odolbeau** [comment]
@fab-kaz Could you give more details regarding your solution please?
Just tried with latest version compose file looking like this one and this is not working on my side.

```yaml
version: '3'

services:
  etherpad:
    image: etherpad/etherpad
    environment:
      # DB config & so on removed
    ports:
      - "9001:9001"
    depends_on:
      - etherpad-db
    volumes:
      - etherpad-plugins:/opt/etherpad-lite/node_modules/

volumes:
  etherpad-plugins:
```

When looking in the created volume (with ls `/var/lib/docker/volumes/{PROJECT_NAME}_etherpad-plugins/_data/` the only file I get is a symlink which point to `../` and anything else.
Downloading plugins from the admin does not work.

**Comment by tommyhlw** [comment]
`version: '3.4'

services:

  pad:
    depends_on:
      - db_pad  
    configs:
      - source: app-settings
        target: /opt/Scripts/docker/etherpad/settings.json
    env_file:
      - pad.env
    volumes:
      - ./pad_storage/_data:/opt/etherpad-lite
      - /etc/localtime:/etc/localtime:ro
    image: etherpad/etherpad:**1.8.15**
    restart: always
    environment:
     - VIRTUAL_HOST=my.etherpadurl.com
     - LETSENCRYPT_HOST=my.etherpadurl.com
  db_pad:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./pad_db_storage/_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $SECRET
      POSTGRES_DB: etherpad
`
you have to explicity use the version tag (in bold) of the image you'd like to use.
Valid tags are here https://hub.docker.com/r/etherpad/etherpad/tags

so you can run image: etherpad/etherpad:**1.8.15** install the plugins via admin page and then run image: etherpad/etherpad:**latest**
I guess it schould also work to downgrade again to **1.8.15** just for installing the plugins

**Comment by odolbeau** [comment]
OK, so if I understand well, downloading plugins with the latest version still doesn't works, does it?
Which means we shouldn't close this ticket as the problem is not resolved.

**Comment by tessierp** [comment]
I can confirm the problem is still there.

**Comment by fab-kaz** [comment]
hello,

@odolbeau 

We use 1.8.18 version and installing plugin with web admin interface works but but but, for the first plugin, you have to wait very long: about 10 minutes in our case ! we didn't checked why the first one was so long to install.
```docker-compose logs -f``` show the progression of installation of the plugin.

here is our docker-compose.yml :
```
# cat docker-compose.yml 
version: '3.3'

services:

  pad:
    image: etherpad/etherpad:1.8.18
    container_name: ${etherpadServName}
    restart: ${restartPolicy}
    depends_on:
      - padDB
    networks:
      - etherpadNet
      - postfixNet
    external_links:
      - ${etherpadDBName}:padDB
      - ${smtpServName}:${smtpHost}
    volumes:
      - etherpadPlugins:/opt/etherpad-lite/node_modules/
      - ${PWD}/settings.json:/opt/etherpad-lite/settings.json
      
    env_file:
      - ../../secret/env-${etherpadServName}
    environment:
      - "DEFAULT_PAD_TEXT=––––– Ce texte est à effacer (après lecture si c’est votre première visite) ou à conserver en bas de votre pad –––––\n\nBienvenue sur notre PAD !\n\n➡ Comment commencer ?\n• Renseignez votre nom ou pseudo, en cliquant sur l’icône « utilisateur » en haut à droite.\n• Choisissez votre couleur d'écriture au même endroit.\n• Lancez-vous : écrivez sur votre pad !\n• Les contributions de chacun se synchronisent « en temps réel » sous leur propre couleur.\n\n➡ Comment partager / collaborer ?\n• Sélectionnez et copiez l'URL (l'adresse web dans la grande barre en haut à gauche du navigateur)\n• Partagez-là à vos collaborateurs et collaboratrices (email, messagerie, etc.)\n• Attention : toute personne ayant cette adresse d'accès peut modifier le pad à sa convenance.\n• Utilisez l'onglet chat (en bas à droite) pour séparer les discussions du texte sur lequel vous travaillez.\n\n➡ Comment sauvegarder ?\n• Il n'y a rien à faire : le texte est automatiquement sauvegardé, à chaque caractère tapé.\n• Marquez une version (un état du pad) en cliquant sur l’icône « étoile ».\n• Retrouvez toute l'évolution du pad et vos versions marquées d'une étoile dans l’historique (icône « horloge »).\n• Importez et exportez votre texte avec l'icône « double flèche » (formats HTML, texte brut) ou avec un copier/coller.\n\nImportant ! N’oubliez pas de conserver quelque part l’adresse web (URL) de votre pad.\n\nBon travail collaboratif :)\n\n––––– Ce texte est à effacer (après lecture si c’est votre première visite) –––––\n\n**ATTENTION**\nCETTE INSTANCE PROPOSE DES PADS À EFFACEMENT AUTOMATIQUE !\n\nVOS PADS SERONT AUTOMATIQUEMENT SUPPRIMÉS AU BOUT DE 62 JOURS (2 MOIS) SANS ÉDITION !\n\nSi le contenu de votre pad bimestriel a été effacé, c'est qu'il n'avait pas été modifié depuis plus de 62 jours consécutifs.\n"

  padDB:
    image: mariadb:10.5
    container_name: ${etherpadDBName}
    restart: ${restartPolicy}
    networks:
      - etherpadNet
    env_file:
      - ../../secret/env-${etherpadDBName}
    volumes:
      - padDB:/var/lib/mysql

volumes:
  padDB:
  etherpadPlugins:
  
networks:
  etherpadNet:
    external:
      name: etherpadNet
  postfixNet:
    external:
      name: postfixNet
```

When i install a new plugin with web interaface:
```
etherpadServ | [2023-04-17 07:50:58.897] [INFO] plugins - Installing plugin ep_adminpads2...
etherpadServ | [2023-04-17 07:51:18.700] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
etherpadServ | [2023-04-17 07:51:18.737] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
etherpadServ | [2023-04-17 07:51:18.775] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
etherpadServ | [2023-04-17 07:51:18.804] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
etherpadServ | [2023-04-17 07:51:18.831] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
etherpadServ | [2023-04-17 07:51:18.831] [ERROR] runCmd|npm - 
etherpadServ | [2023-04-17 07:51:18.834] [INFO] runCmd|npm - + ep_adminpads2@2.1.57
etherpadServ | [2023-04-17 07:51:18.834] [INFO] runCmd|npm - added 24 packages from 8 contributors and audited 1128 packages in 16.606s
etherpadServ | [2023-04-17 07:51:20.205] [INFO] runCmd|npm - 
etherpadServ | [2023-04-17 07:51:20.205] [INFO] runCmd|npm - 59 packages are looking for funding
etherpadServ | [2023-04-17 07:51:20.205] [INFO] runCmd|npm -   run `npm fund` for details
etherpadServ | [2023-04-17 07:51:20.205] [INFO] runCmd|npm - 
etherpadServ | [2023-04-17 07:51:20.209] [INFO] runCmd|npm - found 72 vulnerabilities (16 moderate, 37 high, 19 critical)
etherpadServ | [2023-04-17 07:51:20.209] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
etherpadServ | [2023-04-17 07:51:20.278] [INFO] plugins - Successfully installed plugin ep_adminpads2
etherpadServ | [2023-04-17 07:51:20.280] [INFO] plugins - Running npm to get a list of installed plugins...
etherpadServ | [2023-04-17 07:51:27.745] [INFO] plugins - Loading plugin ep_adminpads2...
etherpadServ | [2023-04-17 07:51:27.745] [INFO] plugins - Loading plugin ep_align...
etherpadServ | [2023-04-17 07:51:27.746] [INFO] plugins - Loading plugin ep_etherpad-lite...
etherpadServ | [2023-04-17 07:51:27.749] [INFO] plugins - Loaded 3 plugins
etherpadServ | [2023-04-17 07:51:28.152] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
etherpadServ | [2023-04-17 07:51:28.161] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpadServ | [2023-04-17 07:51:28.173] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
etherpadServ | [2023-04-17 07:51:28.174] [WARN] settings - Declaring the sessionKey in the settings.json is deprecated. This value is auto-generated now. Please remove the setting from the file. -- If you are seeing this error after restarting using the Admin User Interface then you can ignore this message.
etherpadServ | [2023-04-17 07:51:28.174] [INFO] settings - Random string used for versioning assets: 57da6875
etherpadServ | [2023-04-17 07:51:28.177] [INFO] http - Closing HTTP server...
etherpadServ | [2023-04-17 07:51:28.179] [INFO] socket.io - Closing socket.io engine...
etherpadServ | [2023-04-17 07:51:28.185] [INFO] socket.io - All socket.io clients have disconnected
etherpadServ | [2023-04-17 07:51:28.187] [INFO] http - Waiting for 2 HTTP clients to disconnect...
etherpadServ | [2023-04-17 07:51:28.193] [INFO] http - HTTP server closed
etherpadServ | [2023-04-17 07:51:30.885] [INFO] http - HTTP server listening for connections
etherpadServ | [2023-04-17 07:51:32.404] [INFO] access - [ENTER] pad:DT--4702 socket:RdWu6lmgI3twxkM8AAAm IP:10.0.0.100 authorID:a.V8xNm1gb0t9WqUcE
```
![Capture d’écran_2023-04-17_09-55-39](https://user-images.githubusercontent.com/12799446/232421594-3e84afa1-1652-486f-9b8b-7f28eba19fbe.png)

hope it helps,

f.
