### ISSUE TITLE
Start of docker image fails with error  Cannot find module 'log4js' with DB_TYPE=sqlite

### ISSUE THREAD

**Issue by cybertschunk** [ether/etherpad-lite#5735]
**Describe the bug**
We upgraded to the latest etherpad release and now our etherpad installation refuses to start correctly. It fails with the following error:
```
etherpad    | Error: Cannot find module 'log4js'
etherpad    | Require stack:
etherpad    | - /opt/etherpad-lite/src/node/server.js
etherpad    |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
etherpad    |     at Module._load (node:internal/modules/cjs/loader:920:27)
etherpad    |     at Module.require (node:internal/modules/cjs/loader:1141:19)
etherpad    |     at require (node:internal/modules/cjs/helpers:110:18)
etherpad    |     at Object.<anonymous> (/opt/etherpad-lite/src/node/server.js:27:16)
etherpad    |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
etherpad    |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
etherpad    |     at Module.load (node:internal/modules/cjs/loader:1117:32)
etherpad    |     at Module._load (node:internal/modules/cjs/loader:958:12)
etherpad    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
etherpad    |   code: 'MODULE_NOT_FOUND',
etherpad    |   requireStack: [ '/opt/etherpad-lite/src/node/server.js' ]
etherpad    | }
```

**To Reproduce**
1. We use the following docker compose file
```
version: "3.7"

services:
  etherpad:
    image: etherpad/etherpad
    container_name: etherpad
    volumes:
      - type: bind
        source: TRUNCATED/etherpad/pads.db
        target: /opt/etherpad-lite/var/pads.db
    environment:
      - TITLE=TRUNCATED
      - DB_TYPE=sqlite
      - DB_FILENAME=var/pads.db
      - API_KEY=${ETHERPAD_API_KEY}
      - ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ADMIN_USER=TRUNCATED
    ports:
      - 127.0.0.1:13080:9001
    restart: unless-stopped
    command: bash -c "npm install sqlite3 && node src/node/server.js"
```
3. Run `docker-compose up`
4. Wait for the error

**Expected behavior**
The docker container starts up normally.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: Latest tag
 - OS: Docker Image

**Comment by SamTV12345** [comment]
Thanks for the issue. Did we change anything log4js related yesterday? I can't remember that we did something in that corner @JohnMcLear ?

**Comment by JohnMcLear** [comment]
@SamTV12345 no, we did not.

the Log4JS exploit doesn't impact Etherpad, it is something we need to address in general though..  Afaik the TLDR is that log4js changed the format of their settings blob so anyone with an old settings blob for logs would be unable to use the latest versions..

**Comment by SamTV12345** [comment]
Ok. Thanks for the info. The latest ueber version didn't fix the problem. Maybe installing an older SQLite version might work.

**Comment by jibon57** [comment]
I'm facing almost similar problem with redis. Looks like `ueberdb` not accepting custom host name. It's always using default `127.0.0.1`

```
  "dbType": "redis",
  "dbSettings": {
    "host":     "host.docker.internal",
    "port":     6379
  },
```

**Comment by SamTV12345** [comment]
Im working on it. Unfortunately I couldn't find a fix yet. Do you also install something at startup? Try to add log4js to the initial installation.

**Comment by cybertschunk** [comment]
I tried to install log4js directly as we install sqlite. Unfortunately it still refused to start due to unresolved functions.

**Comment by SamTV12345** [comment]
Is the method named something like setGlobalLogLevel or appenders?

**Comment by cybertschunk** [comment]
the startup fails with the following log output
```
etherpad    | /opt/etherpad-lite/src/node/server.js:28
etherpad    | log4js.replaceConsole();
etherpad    |        ^
etherpad    |
etherpad    | TypeError: log4js.replaceConsole is not a function
etherpad    |     at Object.<anonymous> (/opt/etherpad-lite/src/node/server.js:28:8)
etherpad    |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
etherpad    |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
etherpad    |     at Module.load (node:internal/modules/cjs/loader:1119:32)
etherpad    |     at Module._load (node:internal/modules/cjs/loader:960:12)
etherpad    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
etherpad    |     at node:internal/main/run_main_module:23:47
```

**Comment by JohnMcLear** [comment]
The redis bug is not really related but due to an redis & ueberdb version bump and the docs being straight up wrong for ueberdb & redis.

The TLDR is you should use ``url`` for Redis and someone should probably modify the redis logic to create a url from hostname et al.

**Comment by cybertschunk** [comment]
doing so still causes the server to fail. Now it can't locate the database file anymore
`[2023-06-30 12:02:17.780] [ERROR] server - Error occurred while starting Etherpad
etherpad    | [2023-06-30 12:02:17.781] [ERROR] server - Metrics at time of fatal error:
etherpad    | {
etherpad    |   "httpStartTime": 0,
etherpad    |   "memoryUsage": 76132352,
etherpad    |   "memoryUsageHeap": 19557784
etherpad    | }
etherpad    | [2023-06-30 12:02:17.781] [ERROR] server - Error: SQLITE_CANTOPEN: unable to open database file`

**Comment by SamTV12345** [comment]
I finally found the solution. Seems like the default type is erroring out because no directory is set. 

Given the following docker-compose

```yaml
services:
  etherpad:
    image: etherpad/etherpad:develop
    container_name: etherpad
    volumes:
          - type: bind
            source: ./data
            target: /opt/etherpad-lite/var
          - type: bind
            source: ./settings.json
            target: /opt/etherpad-lite/settings.json
    environment:
      - TITLE=TRUNCATED
      - DB_TYPE=sqlite
      - API_KEY=${ETHERPAD_API_KEY}
      - ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ADMIN_USER=TRUNCATED
    ports:
      - 127.0.0.1:13080:9001
    restart: unless-stopped
    command:  bash -c "cd src && npm install sqlite3 && node node/server.js"
```

Download the attached settings.log and put it in the root directory of your etherpad directory.

Execute this in your bash

```bash
mv settings.log settings.json
nano docker-compose.yml # Take the source from above
```

You should have a data directory in your etherpad directory which contains the sqlite database once the server is up and you e.g. create a pad.



To circumvent the constant download of sqlite you can create a new Dockerfile based on the etherpad image and run the commands in that shell and export that image again. That way you have a completely local file. 





[settings.log](https://github.com/ether/etherpad-lite/files/11926879/settings.log)
