### ISSUE TITLE
Docker upgrade (custom build) : files not copied in container

### ISSUE THREAD

**Issue by Manumie** [ether/etherpad-lite#6048]
**Describe the bug**
After upgrade (following the docs at https://github.com/ether/etherpad-lite/blob/develop/doc/docker.adoc), the new files are not copied into the container's volume

**To Reproduce**
Previous version (1.8.18) was installed from `git clone --branch master https://github.com/ether/etherpad-lite.git`, and it's been working just fine for more than a year

1. enter etherpad dir : `cd etherpad-lite`
2. update the source : `git pull origin` 
3. build the image : `docker build --build-arg INSTALL_ABIWORD=true --tag myrepo/etherpad:base .`
4. restart the container (managed with docker-compose, where the service is named `etherpad`) : `docker-compose up -d --force-recreate etherpad` ; `docker ps` shows the container is actually using the newly-built image
5. go to `https://my.etherpad.url/admin/plugins/info` : version is still 1.8.18 ; last version is 1.9.4
    this is confirmed in the logs : `[INFO] console - Your Etherpad version is 1.8.18 (4b96ff6)`
7. check files in container (managed as a Docker volume and mapped to `/opt/etherpad-lite` in the container) :  
    `diff -uw settings.json.docker /var/lib/docker/volumes/docker_etherpad_vol/_data/settings.json.docker`  
    -> files are not identical (the diff is not relevant in itself)
    -> this is just an example as `diff -urw ./src/bin /var/lib/docker/volumes/docker_etherpad_vol/_data/src/bin` shows many files are not identical
 
**Expected behavior**
Have the latest etherpad version up and running

My guess is that the source tree should have been replaced in the container when I restarted it with `--force-recreate` but I may have misunderstood the process...

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: Debian 12
 - Node.js version : on the server : 20.10.0 ; in the container : 20.10.0
 - npm version (`npm --version`): on the server : 10.2.3 ; in the container : 10.2.3
 - Is the server free of plugins: not relevant ; there were some issues in the logs with ep_tables4, so I removed it

**docker-compose.yml section for the etherpad container**
```
    etherpad:
        image: myrepo/etherpad:base
        restart: unless-stopped
        environment:
            - TITLE=MyEtherpad
            - ADMIN_PASSWORD=secret
            - DB_TYPE=mysql
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_NAME=etherpad
            - DB_USER=etherpad
            - DB_PASS=also_secret
            - DB_CHARSET=utf8mb4
            - ABIWORD=/usr/bin/abiword
            - TRUST_PROXY=true
        networks:
            - web_net
            - maria_net
        volumes:
            - etherpad_vol:/opt/etherpad-lite
        depends_on:
            - mariadb

```
