### ISSUE TITLE
Fatal MySQL error: Error: read ECONNRESET in Docker logs

### ISSUE THREAD

**Issue by janmarcopetri** [ether/etherpad-lite#6099]
**Describe the bug**
Since deploying Etherpad (Docker) version 1.9.6 our pads randomly took forever to open (and to create new ones). Reloading the site multiple times fixes it in the end. Not consistent and not directly reproducable. Happens multiple times over the day, not specific to the same pads.
(Something seems to be incorrect with the data sent/received to/from the MariaDB container.)
Docker logs from Etherpad-Container: Fatal MySQL error: Error: read ECONNRESET (see screenshot below)
Docker logs from MariaDB-Container: Aborted connection [...] error reading communication packets (see screenshot below)

**To Reproduce**
Unfortunately unsure for now...
Deploy a Docker Stack with Etherpad 1.9.6 and MariaDB 10.11 ?

**Expected behavior**
Pads always load and the containers do not produce error logs.

**Screenshots**
![etherpad1](https://github.com/ether/etherpad-lite/assets/98863582/27ac1cdf-4f17-4516-8eb8-647eea3839f6)
![etherpad2](https://github.com/ether/etherpad-lite/assets/98863582/6a3861de-8498-4a6b-b967-e02a1fac1814)

**Server (please complete the following information):**
 - Docker Stack deployed with docker-compose
 - Etherpad version: 1.9.6
 - MariaDB version: 10.11

**Comment by SamTV12345** [comment]
Could you please paste your docker-compose anonymized? Maybe I can reproduce it locally.

**Comment by janmarcopetri** [comment]
Thank you for trying, here you go:

```
version: '3.8'

volumes:
  mariadb:

services:
    
  mariadb:
    image: registry.<domain>/mirror/mariadb:10.11
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_DATABASE=etherpad
      - MARIADB_USER=etherpad
      - MARIADB_PASSWORD=
      #- MARIADB_AUTO_UPGRADE=1
      #- MARIADB_INITDB_SKIP_TZINFO=1    
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1

  etherpad:
    image: registry.<domain>/etherpad:1.9.6
    user: etherpad:etherpad
    environment:
      - TITLE=
      - DEFAULT_PAD_TEXT=
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_CHARSET=utf8mb4
      - DB_PASS=
      - PAD_OPTIONS_LANG=de
      - PAD_OPTIONS_USE_MONOSPACE_FONT=false
      - SOFFICE=/usr/bin/soffice
      - ABIWORD=/usr/bin/abiword
    networks:
      - network
    ports:
      - "10001:9001"
    deploy:
      mode: replicated
      replicas: 1

networks:
  network:
    driver: overlay
```

The MariaDB is the official image from Docker Hub, just mirrored on our own registry server.
The Etherpad image is built following the instructions from this repo, adding:
```
   --build-arg ETHERPAD_PLUGINS="ep_headings2 ep_font_color ep_authornames ep_align" \
    --build-arg INSTALL_ABIWORD=true \
    --build-arg INSTALL_SOFFICE=true
```

Note we are running a Docker Swarm so probably you will have to remove the "deploy" sections for the containers.

**Comment by SamTV12345** [comment]
I added some values in the docker-compose.yml and it works so far.

```yaml
version: '3.8'

volumes:
  mariadb:

services:

  mariadb:
    image: mariadb:10.11
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=etherpad
      - MARIADB_USER=etherpad
      - MARIADB_PASSWORD=test
      - MARIADB_ROOT_PASSWORD=test
      #- MARIADB_AUTO_UPGRADE=1
      #- MARIADB_INITDB_SKIP_TZINFO=1
    networks:
      - network

  etherpad:
    image: etherpad/etherpad:1.9.6
    user: etherpad:etherpad
    environment:
      - TITLE=
      - DEFAULT_PAD_TEXT=
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_CHARSET=utf8mb4
      - DB_PASS=test
      - PAD_OPTIONS_LANG=de
      - PAD_OPTIONS_USE_MONOSPACE_FONT=false
      - SOFFICE=/usr/bin/soffice
      - ABIWORD=/usr/bin/abiword
    networks:
      - network
    ports:
      - "10001:9001"

networks:
  network:
  ```
