### ISSUE TITLE
No Basic Auth 

### ISSUE THREAD

**Issue by notaLonelyDay** [ether/etherpad-lite#6247]
**Describe the bug**
There's no basic auth popup.
As I understand with this settings there should be basic auth popup, I've tried different browsers

All I see in browser is:
`Authentication Required`
And in logs:
```
etherpad  | [2024-03-19T22:23:03.095] [INFO] http - Failed authentication from IP x.x.x.x
etherpad  | [2024-03-19T22:23:04.973] [INFO] http - Failed authentication from IP x.x.x.x
```

My docker-compose:
```
  etherpad:
    container_name: etherpad
    image: etherpad/etherpad

    networks:
      etherpad:

    environment:
      DEFAULT_PAD_TEXT: ""
      ADMIN_PASSWORD: "***"
      USER_PASSWORD: "***"
      PAD_OPTIONS_USE_MONOSPACE_FONT: true
      PAD_OPTIONS_ALWAYS_SHOW_CHAT: true
      PAD_OPTIONS_CHAT_AND_USERS: true
      REQUIRE_AUTHENTICATION: true

    ports:
      - 9001:9001
```

Looks like because of this line:
https://github.com/ether/etherpad-lite/blob/bd2198a70edc427353ec80c645063a6119fad5ca/src/node/hooks/express/webaccess.ts#L172
