### ISSUE TITLE
Docker: ADMIN_PASSWORD is not passing

### ISSUE THREAD

**Issue by Langoor2** [ether/etherpad-lite#6791]
**Describe the bug**
Setup a clean etherpad with mariadb database, as according to the instructions on the Wiki.
If i set "ADMIN_PASSWORD" to any value, this value is not passed/parsed correctly, in the config i can see that it is still set to the default admin password.

**To Reproduce**
1. set "ADMIN_PASSWORD" with docker
2. login to the /admin/ ui
3. the default admin/admin credentials are always accepted
4. in the currently running settings you can see that it is using admin/admin

**Expected behavior**
It uses the admin password I configured

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 2.2.6
 - OS: Ubuntu 22.04
 - Node.js version (`node --version`): came with docker image
 - npm version (`npm --version`): pnpm --version: 9.0.4
 - Is the server free of plugins: Yes

**Additional context**
docker compose:
```
services:
  app:
    user: "0:0"
    image: etherpad/etherpad:latest
    tty: true
    stdin_open: true
    volumes:
      - plugins:/opt/etherpad-lite/src/plugin_packages
      - etherpad-var:/opt/etherpad-lite/var
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: xXx1234aBcDe
      DB_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      DB_NAME: etherpad_db
      DB_PASS: xxxxxx
      DB_PORT: 3306
      DB_TYPE: mysql
      DB_USER: etherpaduser
      DB_CHARSET: utf8mb4
      # For now, the env var DEFAULT_PAD_TEXT cannot be unset or empty; it seems to be mandatory in the latest version of etherpad
      DEFAULT_PAD_TEXT: ${DOCKER_COMPOSE_APP_DEFAULT_PAD_TEXT:- }
      DISABLE_IP_LOGGING: ${DOCKER_COMPOSE_APP_DISABLE_IP_LOGGING:-false}
      SOFFICE: ${DOCKER_COMPOSE_APP_SOFFICE:-null}
      TRUST_PROXY: ${DOCKER_COMPOSE_APP_TRUST_PROXY:-true}
    restart: always
    ports:
      - "${DOCKER_COMPOSE_APP_PORT_PUBLISHED:-9001}:${DOCKER_COMPOSE_APP_PORT_TARGET:-9001}"

volumes:
  plugins:
  etherpad-var:
```
