### ISSUE TITLE
Proxy with authentication not supported

### ISSUE THREAD

**Issue by brunobastosg** [ether/etherpad-lite#6866]
**Describe the bug**
If Etherpad is running behind a corporate proxy with authentication, then some features like installation of plugins don't work.

**To Reproduce**

Run the docker-compose.yml below and try to acess http://0.0.0.0:9001/admin/plugins :

```
services:
  app:
    user: "0:0"
    image: etherpad/etherpad:latest
    tty: true
    stdin_open: true
    volumes:
      - plugins:/opt/etherpad-lite/src/plugin_packages
      - etherpad-var:/opt/etherpad-lite/var
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${DOCKER_COMPOSE_APP_ADMIN_PASSWORD:-admin}
      DB_CHARSET: ${DOCKER_COMPOSE_APP_DB_CHARSET:-utf8mb4}
      DB_HOST: postgres
      DB_NAME: ${DOCKER_COMPOSE_POSTGRES_DATABASE:-etherpad}
      DB_PASS: ${DOCKER_COMPOSE_POSTGRES_PASSWORD:-admin}
      DB_PORT: ${DOCKER_COMPOSE_POSTGRES_PORT:-5432}
      DB_TYPE: "postgres"
      DB_USER: ${DOCKER_COMPOSE_POSTGRES_USER:-admin}
      DEFAULT_PAD_TEXT: ${DOCKER_COMPOSE_APP_DEFAULT_PAD_TEXT:- }
      DISABLE_IP_LOGGING: ${DOCKER_COMPOSE_APP_DISABLE_IP_LOGGING:-false}
      SOFFICE: ${DOCKER_COMPOSE_APP_SOFFICE:-null}
      TRUST_PROXY: ${DOCKER_COMPOSE_APP_TRUST_PROXY:-true}
      https_proxy: http://proxyUser:proxyPass@proxy:3128
    ports:
      - "${DOCKER_COMPOSE_APP_PORT_PUBLISHED:-9001}:${DOCKER_COMPOSE_APP_PORT_TARGET:-9001}"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DOCKER_COMPOSE_POSTGRES_DATABASE:-etherpad}
      POSTGRES_PASSWORD: ${DOCKER_COMPOSE_POSTGRES_PASSWORD:-admin}
      POSTGRES_PORT: ${DOCKER_COMPOSE_POSTGRES_PORT:-5432}
      POSTGRES_USER: ${DOCKER_COMPOSE_POSTGRES_USER:-admin}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    image: yegor256/squid-proxy:latest
    ports:
      - 3128:3128
    environment:
      - USERNAME=proxyUser
      - PASSWORD=proxyPass

volumes:
  postgres_data:
  plugins:
  etherpad-var:
```

**Expected behavior**
It should work.

**Server (please complete the following information):**
 - Etherpad version: 2.2.7
 - OS: Ubuntu 22.04
 - Node.js version (`node --version`): v23.5.0
 - npm version (`npm --version`): 10.9.2
 - Is the server free of plugins: Yes

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 132.0.6834.110

**Additional context**
As far as I know, the problem only occurs if the proxy requires authentication.
